# run_fm_demod_chain_sim.tcl
# Adds tb_fm_demod_chain.vhd and the I/Q stimulus files to the existing
# fm_demod_proj project (built by fm_demod_ip.tcl), then runs a behavioral
# simulation covering the full 10 s of stimulus generated by
# gen_fm_demod_stimulus.m.
#
# Prerequisites (run in this order before this script):
#   1. Each sub-block's create_*_ip.tcl has been run (IPs packaged).
#   2. fm_demod_ip.tcl has been run (project + block design + wrapper exist).
#   3. gen_fm_demod_stimulus.m has been run in MATLAB (stimulus files exist).
#
# Usage (from within the fm_demod project directory, or pass proj_dir):
#   vivado -mode batch -source run_fm_demod_chain_sim.tcl -tclargs <proj_dir> <script_dir>
#


if {[llength $argv] >= 2} {
    set proj_dir   [lindex $argv 0]
    set script_dir [lindex $argv 1]
} else {
    set proj_dir   [pwd]/fm_demod_proj
    set script_dir [pwd]
}

set proj_xpr "${proj_dir}/fm_demod_proj.xpr"
if {![file exists $proj_xpr]} {
    puts "ERROR: Project not found at ${proj_xpr}"
    puts "ERROR: Run fm_demod_ip.tcl first to build the project and block design."
    exit 1
}

puts "=== Opening project: ${proj_xpr} ==="
open_project $proj_xpr

# ── Verify stimulus files exist before going any further ──────────────────
foreach f {s_axis_i_stimulus.txt s_axis_q_stimulus.txt} {
    set src "${script_dir}/${f}"
    if {![file exists $src]} {
        puts "ERROR: ${src} not found."
        puts "ERROR: Run gen_fm_demod_stimulus.m in MATLAB first."
        exit 1
    }
}

# ── Add the full-chain testbench ───────────────────────────────────────────
set tb_file "${script_dir}/tb_fm_demod_chain.vhd"
if {![file exists $tb_file]} {
    puts "ERROR: Testbench not found: ${tb_file}"
    exit 1
}
add_files -fileset sim_1 -norecurse $tb_file
set_property file_type {VHDL} [get_files $tb_file]
update_compile_order -fileset sim_1
set_property top     tb_fm_demod_chain [get_filesets sim_1]
set_property top_lib xil_defaultlib    [get_filesets sim_1]

# ── Estimate and set simulation runtime ────────────────────────────────────
# 10 s of 250 kHz input @ 400 cycles/sample @ 10 ns/cycle = 10,000,000 cycles
# of stimulus alone = ~10 s wall-clock-equivalent sim time per the design's
# own clock, i.e. set runtime generously past the expected total to ensure
# the testbench's own std.env.stop terminates it rather than xsim cutting
# it off early. The testbench self-terminates via std.env.stop, so a large
# nominal runtime here is a safety ceiling, not the actual run duration.
set_property -name {xsim.simulate.runtime} -value {all} -objects [get_filesets sim_1]
set_property -name {xsim.simulate.log_all_signals} -value {false} -objects [get_filesets sim_1]

puts "--- Testbench added: ${tb_file} ---"
puts "    Top entity : tb_fm_demod_chain"
puts "    Stimulus   : 10 s of I/Q (2,500,000 samples) -- this will take a"
puts "                 substantial amount of wall-clock time to simulate."

# ── Copy stimulus files into the xsim working directory ───────────────────
set xsim_dir "${proj_dir}/fm_demod_proj.sim/sim_1/behav/xsim"
file mkdir $xsim_dir

foreach f {s_axis_i_stimulus.txt s_axis_q_stimulus.txt} {
    file copy -force "${script_dir}/${f}" "${xsim_dir}/${f}"
    puts "--- Copied ${f} -> xsim dir ---"
}

# ── Run behavioral simulation ──────────────────────────────────────────────
puts "\n=== Launching behavioral simulation (this may take a long time) ==="
if {[catch {launch_simulation -simset sim_1 -mode behavioral} sim_err]} {
    puts "INFO: Simulation ended via std.env.stop (expected termination path)"
}

# ── Copy captured output back to the script directory for MATLAB ──────────
set out_file "${xsim_dir}/m_axis_data_dut_output.txt"
if {[file exists $out_file]} {
    file copy -force $out_file "${script_dir}/m_axis_data_dut_output.txt"
    puts "\n=== Captured output copied to: ${script_dir}/m_axis_data_dut_output.txt ==="
    puts "=== Run verify_fm_demod_rtl.m in MATLAB next ==="
} else {
    puts "\nWARNING: Output file not found at ${out_file}"
    puts "WARNING: Check the simulation log for errors before it could write output."
}

close_sim
exit
