#!/bin/bash
################################################################################
# build_prj.sh
# Recreates the sdr_fm_receiver Vivado project from prj.tcl in batch mode.
#
# prj.tcl was generated by Vivado on 2026-07-03 and targets:
#   Part  : xc7z020clg400-1
#   Board : Zybo Z7-20 (digilentinc.com:zybo-z7-20:part0:1.2)
#
# The script must be run from the directory containing prj.tcl. The IP
# repository is expected one level above that directory (origin_dir/../).
#
# Usage:
#   ./build_prj.sh                          # default project name: sdr_fm_receiver
#   ./build_prj.sh --project_name my_name   # override project name
#   ./build_prj.sh --origin_dir /some/path  # override origin directory
#
# Marco Aiello, 2024
################################################################################

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

# Default arguments
ORIGIN_DIR="${SCRIPT_DIR}"
PROJECT_NAME="sdr_fm_receiver"
EXTRA_ARGS=""

# Parse optional arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --project_name)
            PROJECT_NAME="$2"
            shift 2
            ;;
        --origin_dir)
            ORIGIN_DIR="$2"
            shift 2
            ;;
        --help)
            echo "Usage: $0 [--project_name <name>] [--origin_dir <path>]"
            echo "  --project_name  Override project name (default: sdr_fm_receiver)"
            echo "  --origin_dir    Override origin directory (default: script directory)"
            exit 0
            ;;
        *)
            echo "Unknown argument: $1"
            echo "Run $0 --help for usage."
            exit 1
            ;;
    esac
done

# Check prerequisites
for f in prj.tcl bd.tcl tb_sdr_fm_receiver.sv; do
    if [ ! -f "${SCRIPT_DIR}/${f}" ]; then
        echo "ERROR: ${f} not found in ${SCRIPT_DIR}"
        exit 1
    fi
    echo "OK     : ${f}"
done
echo ""

if ! command -v vivado &>/dev/null; then
    echo "ERROR: vivado not found on PATH -- source Vivado 2022.2 settings first:"
    echo "  source /tools/Xilinx/Vivado/2022.2/settings64.sh"
    exit 1
fi

# Warn if project directory already exists
if [ -d "${SCRIPT_DIR}/${PROJECT_NAME}" ]; then
    echo "WARNING: Project directory '${PROJECT_NAME}' already exists."
    echo "         Vivado will attempt to recreate it (existing files may be overwritten)."
    echo ""
fi

echo "=== Recreating Vivado project ==="
echo "    Script dir   : ${SCRIPT_DIR}"
echo "    Origin dir   : ${ORIGIN_DIR}"
echo "    Project name : ${PROJECT_NAME}"
echo "    Log          : ${SCRIPT_DIR}/build_prj.log"
echo ""

# Write a small wrapper Tcl that pre-sets the variables prj.tcl looks for,
# then sources prj.tcl. This avoids -tclargs (which prj.tcl's own parser
# intercepts) and the non-existent -set Vivado flag.
WRAPPER_TCL="${SCRIPT_DIR}/_build_wrapper.tcl"
cat > "${WRAPPER_TCL}" << TCLEOF
# prj.tcl now sources bd.tcl internally (instead of the embedded
# cr_bd_design_1 proc), then calls make_wrapper -- all three steps
# (project skeleton, block design, wrapper) happen inside prj.tcl.
# We just pre-set the two variables it looks for, source it, then
# add the VIP testbench to sim_1.

# ── Steps 1-3: project + bd.tcl + make_wrapper (all inside prj.tcl) ──────────
set origin_dir_loc    {${ORIGIN_DIR}}
set user_project_name {${PROJECT_NAME}}
source [file join {${SCRIPT_DIR}} prj.tcl]

# ── Step 4: add testbench to sim_1 ───────────────────────────────────────────
# The PS7 VIP tasks (write_data, read_data, fpga_soft_reset etc.) are
# called via hierarchical reference to the PS7 instance inside the BD --
# no separate VIP IP instance or additional sim files are needed.
puts "\\n=== Adding testbench to sim_1 ==="

set tb_file {${SCRIPT_DIR}/tb_sdr_fm_receiver.sv}

# Add the testbench
add_files -fileset sim_1 -norecurse \$tb_file
set_property file_type {SystemVerilog} [get_files \$tb_file]
update_compile_order -fileset sim_1
set_property top     tb_sdr_fm_receiver [get_filesets sim_1]
set_property top_lib xil_defaultlib     [get_filesets sim_1]
set_property -name {xsim.simulate.runtime} -value {all} -objects [get_filesets sim_1]

puts "=== Testbench added: tb_sdr_fm_receiver ==="
puts "\\n=== Build complete ==="
puts "Project : [get_property DIRECTORY [current_project]]/[get_property NAME [current_project]].xpr"
exit
TCLEOF

stdbuf -oL -eL vivado -mode batch \
    -source "${WRAPPER_TCL}" \
    -log  "${SCRIPT_DIR}/build_prj.log" \
    -journal "${SCRIPT_DIR}/build_prj.jou"

rm -f "${WRAPPER_TCL}"

# Patch the FM demod IP simulation netlist: replace 'design_1_wrapper inst'
# with 'fm_demod_wrapper inst'. The FM demod IP was packaged from a BD also
# named design_1, so its sim netlist references design_1_wrapper -- but the
# actual simulation model is fm_demod_wrapper.v. Without this patch the FM
# demod IP elaborates as a black box with all outputs stuck at 0.
echo ""
echo "=== Adding FM demod IP internal sim files to sim_1 ==="
# The FM demod IP's internal BD sim netlist (design_1.v and its sub-IPs)
# lives in ipshared/d880/sim/ and must be explicitly added to sim_1 so
# xsim can elaborate the full FM demodulator chain rather than treating
# design_1 as a black box with all outputs stuck at 0.
vivado -mode batch -nojournal -nolog << INNER_TCL
open_project ${SCRIPT_DIR}/sdr_fm_receiver/sdr_fm_receiver.xpr
set d880_sim "${SCRIPT_DIR}/sdr_fm_receiver/sdr_fm_receiver.gen/sources_1/bd/sdr_fm_receiver/ipshared/d880/sim"
foreach f [glob -nocomplain "\${d880_sim}/*.v"] {
    add_files -fileset sim_1 -norecurse \$f
    puts "    Added: [file tail \$f]"
}
update_compile_order -fileset sim_1
save_project_as -force
exit
INNER_TCL
echo "=== FM demod IP sim files added ==="

echo ""
echo "=== Done ==="
echo "Project created at: ${SCRIPT_DIR}/${PROJECT_NAME}/${PROJECT_NAME}.xpr"
echo "Log: ${SCRIPT_DIR}/build_prj.log"
echo ""
echo "To open in Vivado GUI:"
echo "  vivado ${SCRIPT_DIR}/${PROJECT_NAME}/${PROJECT_NAME}.xpr"
