#!/bin/bash
# build_freq_corr_ip.sh
# Builds the freq_corr Vivado project in batch mode, runs behavioral
# simulation, packages the block as a Vivado IP, and exits.
# No GUI is opened.
#
# Usage:
#   chmod +x build_freq_corr_ip.sh
#   ./build_freq_corr_ip.sh
#
# Prerequisites:
#   - Vivado 2022.2 sourced
#   - freq_corr.vhd, tb_freq_corr.vhd in the same directory
#   - input_i_stimulus.txt, input_q_stimulus.txt,
#     input_nco_cos_stimulus.txt, input_nco_sin_stimulus.txt,
#     freqcorr_i_golden.txt, freqcorr_q_golden.txt
#     (generated by run_and_extract.m)
#


set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ_DIR="${SCRIPT_DIR}/freq_corr_proj"
TCL_SCRIPT="${SCRIPT_DIR}/create_freq_corr_ip.tcl"

echo "=== Freq Corr IP Build ==="
echo "Script dir : ${SCRIPT_DIR}"
echo "Project dir: ${PROJ_DIR}"
echo ""

# Check prerequisites
missing=0
for f in freq_corr.vhd tb_freq_corr.vhd \
          input_i_stimulus.txt input_q_stimulus.txt \
          input_nco_cos_stimulus.txt input_nco_sin_stimulus.txt \
          freqcorr_i_golden.txt freqcorr_q_golden.txt \
          create_freq_corr_ip.tcl; do
    if [ ! -f "${SCRIPT_DIR}/${f}" ]; then
        echo "MISSING: ${f}"
        missing=1
    else
        echo "OK     : ${f}"
    fi
done

if [ $missing -eq 1 ]; then
    echo ""
    echo "Fix missing files then retry."
    exit 1
fi

if ! command -v vivado &>/dev/null; then
    echo "ERROR: vivado not on PATH -- source Vivado settings first"
    exit 1
fi

echo ""
echo "=== Launching Vivado in batch mode ==="
rm -rf "${PROJ_DIR}"

vivado -mode batch \
       -source "${TCL_SCRIPT}" \
       -tclargs "${PROJ_DIR}" "${SCRIPT_DIR}" \
       -log "${SCRIPT_DIR}/freq_corr_vivado.log" \
       -journal "${SCRIPT_DIR}/freq_corr_vivado.jou"

echo ""
echo "=== Done ==="
echo "IP packaged to: ${PROJ_DIR}/ip_repo"
echo "Log           : ${SCRIPT_DIR}/freq_corr_vivado.log"
