-- tb_freq_corr.vhd
-- Testbench for freq_corr entity (4 separate AXI-S inputs, 2 separate
-- AXI-S outputs).
-- Reads four stimulus files and two golden output files generated by
-- run_and_extract.m from fm_demod_fixed.slx.
--
-- Stimulus files (inputs):
--   input_i_stimulus.txt       : I_in  sfix16_En15 signed integers
--   input_q_stimulus.txt       : Q_in  sfix16_En15 signed integers
--   input_nco_cos_stimulus.txt : cos   sfix16_En15 signed integers
--   input_nco_sin_stimulus.txt : sin   sfix16_En15 signed integers
--
-- Golden output files:
--   freqcorr_i_golden.txt      : Ic_out sfix18_En17 signed integers
--   freqcorr_q_golden.txt      : Qc_out sfix18_En17 signed integers
--
-- Pipeline latency: 2 clock cycles (1 multiply stage + 1 adder stage).
-- SKIP_SAMPLES=0: 2-cycle pipeline delay fits within one 400-cycle sample
-- period, so DUT output N corresponds to stim input N with no warmup
-- outputs to discard.
--
-- Pass criterion: all samples within TOLERANCE LSBs of golden.
--
-- Marco Aiello, 2024

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb_freq_corr is
end entity tb_freq_corr;

architecture sim of tb_freq_corr is

    constant CLK_PERIOD   : time    := 10 ns;
    constant SAMPLE_RATE  : integer := 400;     -- cycles per sample (100M/250k)
    constant TOLERANCE    : integer := 2;        -- LSBs
    constant N_SAMPLES    : integer := 9990;     -- samples to compare
    constant SKIP_SAMPLES : integer := 0;        -- no skip needed: 2-cycle pipeline

    -- Stimulus files
    constant I_STIM_FILE   : string := "input_i_stimulus.txt";
    constant Q_STIM_FILE   : string := "input_q_stimulus.txt";
    constant COS_STIM_FILE : string := "input_nco_cos_stimulus.txt";
    constant SIN_STIM_FILE : string := "input_nco_sin_stimulus.txt";

    -- Golden files
    constant IC_GOLD_FILE  : string := "freqcorr_i_golden.txt";
    constant QC_GOLD_FILE  : string := "freqcorr_q_golden.txt";

    -- DUT output files
    constant IC_DUT_FILE   : string := "freqcorr_ic_dut_output.txt";
    constant QC_DUT_FILE   : string := "freqcorr_qc_dut_output.txt";

    -- DUT signals: four separate AXI-S slave interfaces
    signal aclk     : std_logic := '0';
    signal aresetn  : std_logic := '0';

    signal s_axis_i_tdata     : std_logic_vector(15 downto 0) := (others => '0');
    signal s_axis_i_tvalid    : std_logic := '0';
    signal s_axis_i_tready    : std_logic;

    signal s_axis_q_tdata     : std_logic_vector(15 downto 0) := (others => '0');
    signal s_axis_q_tvalid    : std_logic := '0';
    signal s_axis_q_tready    : std_logic;

    signal s_axis_cos_tdata   : std_logic_vector(15 downto 0) := (others => '0');
    signal s_axis_cos_tvalid  : std_logic := '0';
    signal s_axis_cos_tready  : std_logic;

    signal s_axis_sin_tdata   : std_logic_vector(15 downto 0) := (others => '0');
    signal s_axis_sin_tvalid  : std_logic := '0';
    signal s_axis_sin_tready  : std_logic;

    -- Two separate AXI-S master interfaces
    signal m_axis_ic_tdata  : std_logic_vector(17 downto 0);
    signal m_axis_ic_tvalid : std_logic;
    signal m_axis_qc_tdata  : std_logic_vector(17 downto 0);
    signal m_axis_qc_tvalid : std_logic;

begin

    aclk <= not aclk after CLK_PERIOD / 2;

    rst_proc : process
    begin
        aresetn <= '0';
        wait for 16 * CLK_PERIOD;
        aresetn <= '1';
        wait;
    end process;

    dut : entity work.freq_corr
        port map (
            aclk               => aclk,
            aresetn            => aresetn,

            s_axis_i_tdata     => s_axis_i_tdata,
            s_axis_i_tvalid    => s_axis_i_tvalid,
            s_axis_i_tready    => s_axis_i_tready,

            s_axis_q_tdata     => s_axis_q_tdata,
            s_axis_q_tvalid    => s_axis_q_tvalid,
            s_axis_q_tready    => s_axis_q_tready,

            s_axis_cos_tdata   => s_axis_cos_tdata,
            s_axis_cos_tvalid  => s_axis_cos_tvalid,
            s_axis_cos_tready  => s_axis_cos_tready,

            s_axis_sin_tdata   => s_axis_sin_tdata,
            s_axis_sin_tvalid  => s_axis_sin_tvalid,
            s_axis_sin_tready  => s_axis_sin_tready,

            m_axis_ic_tdata    => m_axis_ic_tdata,
            m_axis_ic_tvalid   => m_axis_ic_tvalid,
            m_axis_ic_tready   => '1',

            m_axis_qc_tdata    => m_axis_qc_tdata,
            m_axis_qc_tvalid   => m_axis_qc_tvalid,
            m_axis_qc_tready   => '1'
        );

    ---------------------------------------------------------------------------
    -- Stimulus process: drives all four input streams together at 250 kHz
    -- (every SAMPLE_RATE cycles). All four tvalid pulses are asserted on the
    -- same clock edge since the DUT requires all four to be valid together.
    ---------------------------------------------------------------------------
    stim_proc : process
        file     f_i   : text;
        file     f_q   : text;
        file     f_cos : text;
        file     f_sin : text;
        variable ln    : line;
        variable vi    : integer;
        variable vq    : integer;
        variable vcos  : integer;
        variable vsin  : integer;
    begin
        file_open(f_i,   I_STIM_FILE,   read_mode);
        file_open(f_q,   Q_STIM_FILE,   read_mode);
        file_open(f_cos, COS_STIM_FILE, read_mode);
        file_open(f_sin, SIN_STIM_FILE, read_mode);

        wait until aresetn = '1';
        wait until rising_edge(aclk);

        for i in 0 to N_SAMPLES + SKIP_SAMPLES - 1 loop
            readline(f_i,   ln); read(ln, vi);
            readline(f_q,   ln); read(ln, vq);
            readline(f_cos, ln); read(ln, vcos);
            readline(f_sin, ln); read(ln, vsin);

            s_axis_i_tdata   <= std_logic_vector(to_signed(vi,   16));
            s_axis_q_tdata   <= std_logic_vector(to_signed(vq,   16));
            s_axis_cos_tdata <= std_logic_vector(to_signed(vcos, 16));
            s_axis_sin_tdata <= std_logic_vector(to_signed(vsin, 16));

            s_axis_i_tvalid   <= '1';
            s_axis_q_tvalid   <= '1';
            s_axis_cos_tvalid <= '1';
            s_axis_sin_tvalid <= '1';

            -- Hold for one clock cycle (tvalid pulse)
            wait until rising_edge(aclk);
            s_axis_i_tvalid   <= '0';
            s_axis_q_tvalid   <= '0';
            s_axis_cos_tvalid <= '0';
            s_axis_sin_tvalid <= '0';

            -- Wait for rest of sample period
            for c in 2 to SAMPLE_RATE loop
                wait until rising_edge(aclk);
            end loop;
        end loop;

        file_close(f_i);
        file_close(f_q);
        file_close(f_cos);
        file_close(f_sin);
        wait;
    end process stim_proc;

    ---------------------------------------------------------------------------
    -- Ic checker
    ---------------------------------------------------------------------------
    ic_check_proc : process
        file     f_gold : text;
        file     f_dut  : text;
        variable ln     : line;
        variable gold   : integer;
        variable dut    : integer;
        variable err    : integer;
        variable n_err  : integer := 0;
        variable n_chk  : integer := 0;
        variable max_e  : integer := 0;
    begin
        file_open(f_gold, IC_GOLD_FILE, read_mode);
        file_open(f_dut,  IC_DUT_FILE,  write_mode);

        wait until aresetn = '1';
        wait until rising_edge(aclk);

        for s in 1 to SKIP_SAMPLES loop
            wait until m_axis_ic_tvalid = '1' and rising_edge(aclk);
            wait until m_axis_ic_tvalid = '0' and rising_edge(aclk);
        end loop;

        for i in 0 to N_SAMPLES - 1 loop
            wait until m_axis_ic_tvalid = '1' and rising_edge(aclk);

            dut := to_integer(signed(m_axis_ic_tdata));
            readline(f_gold, ln); read(ln, gold);
            write(ln, dut); writeline(f_dut, ln);

            err := abs(dut - gold);
            if err > max_e then max_e := err; end if;
            if err > TOLERANCE then
                report "IC MISMATCH sample " & integer'image(i) &
                       ": DUT=" & integer'image(dut) &
                       " GOLD=" & integer'image(gold) &
                       " ERR=" & integer'image(err) & " LSB"
                severity warning;
                n_err := n_err + 1;
            end if;
            n_chk := n_chk + 1;

            wait until m_axis_ic_tvalid = '0' and rising_edge(aclk);
        end loop;

        file_close(f_gold);
        file_close(f_dut);

        report "========================================"  severity note;
        report "IC results" severity note;
        report "  Samples  : " & integer'image(n_chk) severity note;
        report "  Max err  : " & integer'image(max_e) & " LSB" severity note;
        report "  Errors   : " & integer'image(n_err) severity note;
        if n_err = 0 then
            report "  IC: PASS" severity note;
        else
            report "  IC: FAIL" severity failure;
        end if;
        report "========================================"  severity note;
        wait;
    end process ic_check_proc;

    ---------------------------------------------------------------------------
    -- Qc checker
    ---------------------------------------------------------------------------
    qc_check_proc : process
        file     f_gold : text;
        file     f_dut  : text;
        variable ln     : line;
        variable gold   : integer;
        variable dut    : integer;
        variable err    : integer;
        variable n_err  : integer := 0;
        variable n_chk  : integer := 0;
        variable max_e  : integer := 0;
    begin
        file_open(f_gold, QC_GOLD_FILE, read_mode);
        file_open(f_dut,  QC_DUT_FILE,  write_mode);

        wait until aresetn = '1';
        wait until rising_edge(aclk);

        for s in 1 to SKIP_SAMPLES loop
            wait until m_axis_qc_tvalid = '1' and rising_edge(aclk);
            wait until m_axis_qc_tvalid = '0' and rising_edge(aclk);
        end loop;

        for i in 0 to N_SAMPLES - 1 loop
            wait until m_axis_qc_tvalid = '1' and rising_edge(aclk);

            dut := to_integer(signed(m_axis_qc_tdata));
            readline(f_gold, ln); read(ln, gold);
            write(ln, dut); writeline(f_dut, ln);

            err := abs(dut - gold);
            if err > max_e then max_e := err; end if;
            if err > TOLERANCE then
                report "QC MISMATCH sample " & integer'image(i) &
                       ": DUT=" & integer'image(dut) &
                       " GOLD=" & integer'image(gold) &
                       " ERR=" & integer'image(err) & " LSB"
                severity warning;
                n_err := n_err + 1;
            end if;
            n_chk := n_chk + 1;

            wait until m_axis_qc_tvalid = '0' and rising_edge(aclk);
        end loop;

        file_close(f_gold);
        file_close(f_dut);

        report "========================================"  severity note;
        report "QC results" severity note;
        report "  Samples  : " & integer'image(n_chk) severity note;
        report "  Max err  : " & integer'image(max_e) & " LSB" severity note;
        report "  Errors   : " & integer'image(n_err) severity note;
        if n_err = 0 then
            report "  QC: PASS" severity note;
        else
            report "  QC: FAIL" severity failure;
        end if;
        report "========================================"  severity note;

        std.env.stop;
        wait;
    end process qc_check_proc;

end architecture sim;
