//------------------------------------------------------------------------------
// tb_fm_demod_axis_vip.sv
//
// AXI4-Stream VIP testbench for design_1_wrapper (FM demodulator with
// iq_splitter and tlast_gen). Uses Xilinx AXI4-Stream VIP to drive the
// slave input port (s) and monitor the master output port (m), checking
// that neither bus stalls (i.e. tvalid/tready never stay asserted without
// a transaction for more than STALL_TIMEOUT cycles).
//
// Interface under test (design_1_wrapper):
//   s         : AXI-S slave  32-bit, packed {Q[15:0],I[15:0]} from DMA
//   m         : AXI-S master 32-bit, de-emphasis audio + tlast
//   aclk      : 100 MHz clock
//   aresetn   : active-low synchronous reset
//
// Stall detection:
//   A stall is defined as tvalid=1 AND tready=0 for more than
//   STALL_TIMEOUT consecutive clock cycles. This would indicate the
//   downstream consumer or upstream producer is blocking the stream.
//
// The VIP master drives SAMPLE_COUNT packed I/Q beats at 250 kHz rate
// (one beat every SAMPLE_PERIOD cycles). The VIP slave accepts all output
// beats immediately (tready always high). After SAMPLE_COUNT beats the
// testbench checks no stalls occurred and calls $finish.
//
// Marco Aiello, 2024
//------------------------------------------------------------------------------
`timescale 1ns / 1ps

// Import AXI4-Stream VIP packages (generated by IP Integrator)
import axi4stream_vip_pkg::*;
// NOTE: replace these two package names with the actual names generated
// by Vivado for your VIP instances. Find them with:
//   find <proj_dir> -name "*pkg*" | grep -i vip
// They typically follow the pattern: <bd_name>_<vip_instance_name>_pkg
import axi4stream_vip_0_pkg::*;   // master VIP (drives s)  -- ADJUST NAME
import axi4stream_vip_1_pkg::*;   // slave  VIP (monitors m) -- ADJUST NAME

module tb_fm_demod_axis_vip;

    //--------------------------------------------------------------------------
    // Parameters
    //--------------------------------------------------------------------------
    localparam time CLK_PERIOD     = 10ns;    // 100 MHz
    localparam int  SAMPLE_PERIOD  = 400;     // cycles per 250 kHz input beat
    localparam int  SAMPLE_COUNT   = 5000;    // I/Q beats to inject
    localparam int  STALL_TIMEOUT  = 1000;    // max cycles tvalid=1,tready=0

    //--------------------------------------------------------------------------
    // DUT signals
    //--------------------------------------------------------------------------
    logic        aclk    = 1'b0;
    logic        aresetn = 1'b0;

    // AXI-S slave port (s): VIP master drives this
    logic [31:0] s_tdata;
    logic        s_tvalid;
    logic        s_tready;
    logic        s_tlast;

    // AXI-S master port (m): VIP slave monitors this
    logic [31:0] m_tdata;
    logic        m_tvalid;
    logic        m_tready;
    logic        m_tlast;

    // Drive SAMPLE_COUNT packed I/Q beats at 250 kHz rate
    // Declare loop-local variables before the loop (xsim does not
    // support inline automatic declarations inside for loops)
    logic [15:0] I_val;
    logic [15:0] Q_val;
    logic [31:0] packed_iq;   // 'packed' is a SV keyword -- use packed_iq

    //--------------------------------------------------------------------------
    // Clock
    //--------------------------------------------------------------------------
    always #(CLK_PERIOD/2) aclk = ~aclk;

    //--------------------------------------------------------------------------
    // DUT
    //--------------------------------------------------------------------------
    design_1_wrapper dut (
        .aclk    (aclk),
        .aresetn (aresetn),
        // Slave input (packed I/Q)
        .s_tdata  (s_tdata),
        .s_tvalid (s_tvalid),
        .s_tready (s_tready),
        .s_tlast  (s_tlast),
        // Master output (audio + tlast)
        .m_tdata  (m_tdata),
        .m_tvalid (m_tvalid),
        .m_tready (m_tready),
        .m_tlast  (m_tlast)
    );

    //--------------------------------------------------------------------------
    // AXI4-Stream VIP instances
    // NOTE: the exact module names and package names depend on how the VIP
    // is instantiated in your block design. Adjust the instance names below
    // to match the VIP cell names in design_1 (visible in the IP Integrator
    // diagram or bd.tcl). The package imports at the top must match too.
    //--------------------------------------------------------------------------
    // Master VIP agent (drives s)
    axi4stream_vip_0_mst_t  mst_agent;   // ADJUST type name to match package

    // Slave VIP agent (monitors m, always-ready consumer)
    axi4stream_vip_1_slv_t  slv_agent;   // ADJUST type name to match package

    //--------------------------------------------------------------------------
    // Stall counters
    //--------------------------------------------------------------------------
    int s_stall_cnt  = 0;   // cycles s_tvalid=1, s_tready=0
    int m_stall_cnt  = 0;   // cycles m_tvalid=1, m_tready=0
    int s_stall_max  = 0;
    int m_stall_max  = 0;
    int s_stall_err  = 0;
    int m_stall_err  = 0;

    //--------------------------------------------------------------------------
    // Stall monitor: samples every clock and tracks consecutive stall cycles
    //--------------------------------------------------------------------------
    always @(posedge aclk) begin
        if (aresetn) begin
            // Input stall monitor
            if (s_tvalid && !s_tready) begin
                s_stall_cnt++;
                if (s_stall_cnt > s_stall_max) s_stall_max = s_stall_cnt;
                if (s_stall_cnt > STALL_TIMEOUT) begin
                    $error("INPUT STALL: s_tvalid=1, s_tready=0 for %0d cycles (limit=%0d)",
                           s_stall_cnt, STALL_TIMEOUT);
                    s_stall_err++;
                end
            end else begin
                s_stall_cnt = 0;
            end

            // Output stall monitor
            if (m_tvalid && !m_tready) begin
                m_stall_cnt++;
                if (m_stall_cnt > m_stall_max) m_stall_max = m_stall_cnt;
                if (m_stall_cnt > STALL_TIMEOUT) begin
                    $error("OUTPUT STALL: m_tvalid=1, m_tready=0 for %0d cycles (limit=%0d)",
                           m_stall_cnt, STALL_TIMEOUT);
                    m_stall_err++;
                end
            end else begin
                m_stall_cnt = 0;
            end
        end
    end

    //--------------------------------------------------------------------------
    // Main test sequence
    //--------------------------------------------------------------------------
    initial begin : test_proc
        axi4stream_transaction  wr_trans;
        xil_axi4stream_data_byte  data_bytes[];
        int i;

        $display("=== FM Demod AXI-S VIP Stall Test ===");
        $display("    Samples     : %0d", SAMPLE_COUNT);
        $display("    Sample rate : 100MHz / %0d = %.1f kHz", SAMPLE_PERIOD,
                  100000.0 / SAMPLE_PERIOD);
        $display("    Stall limit : %0d cycles", STALL_TIMEOUT);
        $display("");

        // Create and start VIP agents
        mst_agent = new("master vip agent",
                         dut.design_1_i.axi4stream_vip_0.inst.IF);
        slv_agent = new("slave vip agent",
                         dut.design_1_i.axi4stream_vip_1.inst.IF);
        mst_agent.start_master();
        slv_agent.start_slave();

        // Reset sequence
        aresetn = 1'b0;
        repeat (16) @(posedge aclk);
        aresetn = 1'b1;
        @(posedge aclk);

        $display("Reset released. Injecting %0d I/Q sample pairs...", SAMPLE_COUNT);



        for (i = 0; i < SAMPLE_COUNT; i++) begin
            wr_trans = mst_agent.driver.create_transaction("iq_beat");

            // Pack I/Q: I in [15:0], Q in [31:16]
            // Use a slowly-varying synthetic sinusoid approximation
            I_val    = 16'(integer'(4000.0 * $sin(2.0 * 3.14159 * i / 250.0)));
            Q_val    = 16'(integer'(4000.0 * $cos(2.0 * 3.14159 * i / 250.0)));
            packed_iq = {Q_val, I_val};

            data_bytes = new[4];
            data_bytes[0] = packed_iq[ 7: 0];
            data_bytes[1] = packed_iq[15: 8];
            data_bytes[2] = packed_iq[23:16];
            data_bytes[3] = packed_iq[31:24];

            wr_trans.set_data(data_bytes);
            wr_trans.set_last(0);

            mst_agent.driver.send(wr_trans);

            // Wait for the rest of the 250 kHz sample period before next beat
            repeat (SAMPLE_PERIOD - 1) @(posedge aclk);

            if (i % 1000 == 999)
                $display("    Injected %0d / %0d samples (%0.1f ms)",
                          i+1, SAMPLE_COUNT, (i+1) / 250.0);
        end

        // Allow pipeline to flush
        $display("Stimulus complete. Waiting for pipeline flush...");
        repeat (5000) @(posedge aclk);

        // Report
        $display("");
        $display("=== Stall Report ===");
        $display("    Input  (s): max consecutive stall = %0d cycles, errors = %0d",
                  s_stall_max, s_stall_err);
        $display("    Output (m): max consecutive stall = %0d cycles, errors = %0d",
                  m_stall_max, m_stall_err);

        if (s_stall_err == 0 && m_stall_err == 0) begin
            $display("=== PASS: No stalls detected on either bus ===");
        end else begin
            $error("=== FAIL: Stalls detected -- see errors above ===");
        end

        $finish;
    end

endmodule
