#include "aa_lpf.h"
#include "coefficients.h"  // Pulls the 'c' matrix generated by MATLAB

/**
 * Top-Level Function: Single-Channel Anti-Aliasing Low-Pass Filter, AXI-S I/O
 * ------------------------------------------------------------------------------
 * Instantiate one copy per channel (I and Q) -- no internal multiplexing.
 * x/y are mapped to native AXI-Stream (s_axis_x / m_axis_y) via HLS pragmas,
 * giving tdata/tvalid/tready handshake signals directly on export.
 *
 * DSP usage: the MAC_Loop itself carries the PIPELINE pragma (with a fixed
 * II), not the enclosing function. This is the idiomatic HLS pattern for
 * genuine resource sharing -- HLS schedules NTAPS sequential MAC operations
 * through II*NTAPS cycles, reusing a small, fixed number of DSP48 instances
 * (bound by the multiplier/adder count needed for one MAC, not by NTAPS).
 * Wrapping the *function* in PIPELINE instead (as in the previous revision)
 * forces full unrolling of everything inside it regardless of inner UNROLL
 * factors, which is why that approach still produced ~118 DSPs.
 *
 * At II=1 per tap and 129 taps, MAC_Loop takes ~129 cycles to complete one
 * sample -- comfortably inside the 400-cycle budget at 100 MHz clock vs.
 * 250 kHz sample rate, while using only a handful of DSP48 slices.
 *
 * @param x : Incoming data sample, fixdt(1,18,17) format. AXI-S slave.
 * @param y : Filtered output sample, fixdt(1,18,17) with saturation. AXI-S master.
 */
void aa_lpf(data_t &x, data_t &y) {

    #pragma HLS INTERFACE mode=axis port=x
    #pragma HLS INTERFACE mode=axis port=y
    #pragma HLS INTERFACE mode=ap_ctrl_none port=return

    // Single-channel tapped delay line
    static data_t shift_reg[NTAPS] = {0};

    // Shift the delay line and insert the new sample first.
    SHIFT_Loop:
    for (int i = NTAPS - 1; i > 0; i--) {
        shift_reg[i] = shift_reg[i - 1];
    }
    shift_reg[0] = x;

    // 40-bit accumulator matches fixdt(1,40,17) precision with saturation
    acc_t acc = 0;

    // Direct Form FIR Multiply-Accumulate Structure.
    // PIPELINE on the LOOP (not the function) is what actually gives HLS
    // permission to reuse a small set of multiplier/adder instances across
    // sequential iterations, rather than instantiating NTAPS of them.
    MAC_Loop:
    for (int i = 0; i < NTAPS; i++) {
        #pragma HLS PIPELINE II=1
        acc += shift_reg[i] * c[i];
    }

    // Assigning the 40-bit accumulator to the 18-bit output data type
    // automatically enforces standard Floor rounding (truncation) and
    // checks for saturation limits.
    y = acc;
}
